### ISSUE TITLE
PostChanges() timeout not occur

### ISSUE THREAD

**Issue by groezing** [IBM/cloudant-node-sdk#1048]
postChanges() call does never return, seems to hang forever even the timeout duration is reached.

I have following function in my client code to run postChanges() in an endless loop

```

function setupFollow(seq) {
 try {   
     db.postChanges({"db":self.databaseName  "feed":"longpoll","timeout": 60000,"since": seq,"includeDocs" : true })
     .then(response => {
          logger.info(method,  numOfChangesDetected + " changes records received from configDB with last seq : ", lastSeq);
          ........
          setupFollow(lastSeq) 
     .catch( (err) => {
                logger.error(method, "Failed to read trigger config info in configDB with  error : ",err);
                //** Continue to try to read from configDB after a retry wait time  with initial seq_nr  	
                setTimeout( () => {setupFollow( seq );}, retryDelay );	 
                logger.error(method, ": Error while read on provider DB : " + err , "will retry to read in ", retryDelay, " seconds");
     })
 } catch (err) {
    logger.error(method, ": Error in setting up change listener on provider DB : " + err , "will retry to read in 3 seconds");
    //** Continue to try to read from configDB after a retry wait time  with initial seq_nr   
    setTimeout( () => {setupFollow( seq );}, 1000 );	
 }
}
```

Error situation: The logs over days show, that the setupFollow() is called in a loop. But then it stopped at one single call:
logline:
Dec 18 12:06:15 alarmstrigger-01-worker-76f44f7cc9-4dllr alarmstrigger-01-worker INFO [??] [alarmsTrigger] [setupFollow] Next trigger configDB read sequence starts on : [ 1520029-g1AAAAObeJzLYWBg4MhgTmFQTklKzi9KdUhJMtZLytUtz8gszjYwNNJLzskvTUnMK9HLSy3JASpmSmRIkv___39WBnMSA9Mjs1ygGHtqWpKhaXIycaaQZFuSApBMsodbeF8bbKGZgVlKmoUJLSx0AFkYD7fwwzqwhRYmhmkWaea0sDABZGE9wocPwBYam5ilJial0MDCPBYgydAApIB2zodY-rYabKmJpamZRWoizSxdALF0P8TSF1fBlqZYGBgYpSbRzNIDEEvvQyx9ehliqUmyqaWRGc0sfQCxFBqnj7shwWtumJiUbECcYVkABNIoEQ ] 

Investigtion on cloudant DB server side showed that the HTTP reqeust for SeqNr: 1520029- did not reached server.

```
Dec 18 12:06:14 lb2.bm-whisk012 haproxy[26686]: 128.168.73.83:36817 -> since=1520027-g1AAAAObe
Dec 18 12:06:15 lb2.bm-whisk012 haproxy[26686]: 128.168.73.83:36817 -> since=1520028-g1AAAAObe
```

Question: Is there a known or possible error case in the postChanges() call that is suppressing the timeout

**Comment by ricellis** [comment]
>Is there a known or possible error case in the postChanges() call that is suppressing the timeout

There is a [known issue](https://github.com/cloudant/couchbackup/issues/527) where axios suppresses connection errors, but we have no reports of timeout suppression. There is nothing specific about `postChanges` that makes it more likely to suppress a timeout than any of the other calls in the library, but the nature of calling it frequently and the requests having typically longer durations than many other requests might increase the probability of encountering connection problems.

There are a number of reported issues in the underlying `axios` HTTP library for issues with timeouts not firing for:
* interupted responses (i.e. partial responses)
* connection aborts
* errors when connecting

Many of these appear to have been closed out with "please try in the latest version" and there certainly appear to be a number of PRs related to timeouts and connection aborts. We have work [underway in the SDK core](https://github.com/IBM/node-sdk-core/pull/217) to upgrade to a newer `axios` version.

I think that trying with the next release is the current best course of action. If the problem persists after that then we'll likely need a reproduce with [client-side `debug` level logging](https://cloud.ibm.com/apidocs/cloudant?code=node#logging) to better identify the exact state of the connection when the problem occurs.

**Comment by groezing** [comment]
Thx for the update.  The intention is to have this issue documented.  I will add a   wrapper function around the  postChanges() call to get a timeout in any case. 
For further investigations with the next axios version we can cooperate again

**Comment by ricellis** [comment]
@groezing suggest you try to reproduce with the [`0.4.0` release](https://github.com/IBM/cloudant-node-sdk/releases/tag/v0.4.0) that includes a more modern `axios` version.

**Comment by ricellis** [comment]
Closing as stale, but please do let us know if this is still a problem.
