### ISSUE TITLE
ibm-cloud-sdk-core is now 4.0.0 which includes major upgrade of axios

### ISSUE THREAD

**Issue by huineng** [IBM/cloudant-node-sdk#1051]
i see you updated dependencies for ibm-cloud-sdk-core
https://github.com/IBM/cloudant-node-sdk/pull/1050

Could you please publish a new package ?
maybe not under 0.3.x ? as contains major release of axios

thanks

**Comment by eiri** [comment]
Yes, we are planning to do a new sdks release in next 2-3 weeks, depending on people availability, it's a holiday season after all.

We don't usually do separate per sdk releases for deps' updates unless for the security fixes. Been generated sdks we are usually sync our releases with generator and openapi specs updates across all the languages we are supporting.

**Comment by huineng** [comment]
of course, thanks and enjoy your holidays 🎄🎄🎄

**Comment by eiri** [comment]
And here it is https://github.com/IBM/cloudant-node-sdk/releases/tag/v0.4.0

It took a bit of a detour because of CVE in core's 4.0.0, so it has core v4.0.2
