### ISSUE TITLE
jsonwebtoken vulnerability detected because of ibm-cloud-sdk-core old version

### ISSUE THREAD

**Issue by mkrudele** [IBM/cloudant-node-sdk#1063]
**Describe the bug**

npm detects the jsonwebtoken vulnerability fixed with the versions >=9.0.0. The vulnerability comes with ibm-cloud-sdk-core, which fixed it in 4.0.2.  
The cloudant module should be udpated to use the latest ibm-cloud-sdk-core version.

**Comment by mojito317** [comment]
Hi @mkrudele! Thank you for your report! We are working on it and presumably will update the master branch with the latest core version tomorrow. We release a new version around the end of every month, but considering this issue the release may occur earlier, this is what our team needs to discuss.

**Comment by mojito317** [comment]
@mkrudele the latest (https://github.com/IBM/cloudant-node-sdk/releases/tag/v0.4.0) release has the `4.0.2` core version. I'm closing this issue.
