### ISSUE TITLE
Support for Node v20

### ISSUE THREAD

**Issue by Shankar-CodeJunkie** [IBM/cloudant-node-sdk#1344]
**Describe the bug**
IBM Cloud functions has jumped from supporting Node 18 and gone straight to Node 20 as a supported runtime, however IBM Cloudant SDK  "@ibm-cloud/cloudant": "^0.7.1"  has not yet been updated to include Node.js 20 support.

When I install the package, I am getting the below warning message, however I do see that I can use the SDK and establish a Cloudant successfully. 

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE  package: '@ibm-cloud/cloudant@0.5.5',
npm WARN EBADENGINE  required: { node: '^16 || ^18' },
npm WARN EBADENGINE  current: { node: 'v20.8.0', npm: '10.1.0' }
npm WARN EBADENGINE }
```

Is it safe to disregard these warning messages and assume that the SDK will continue to work properly with Cloudant ?

**Must gather (please complete the following information):**
 - SDK Version ["@ibm-cloud/cloudant": "^0.7.1"]
 - Node.js Version [e.g. Node.js 20]
 - Name of service that you're trying to use (if applicable)
 - Name of operation that you're trying to invoke (if applicable)

**Comment by eiri** [comment]
We are not officially supporting Node 20 until Oct 24 when it'll become an active LTS, but there are no known issues with this node version and our sdk 0.7.1 was tested with it too, so it shouldn't be a game stopper, just precede with caution.
