### ISSUE TITLE
Please add documentation for the retry mechanisms

### ISSUE THREAD

**Issue by andrewmartin000** [IBM/cloudant-node-sdk#1349]
**Describe the bug**

I am connecting to databases and getting socket hang up errors.   I understand this is probably a network issue and I just need to retry.

I've found other issues reported on this site about the fact that the library has a built in retry feature - but I can't find details of how to use it.   I assume that it's the same retry feature that's docuemnted here: https://github.com/IBM/ibm-cloud-sdk-common/#automatic-retries

However I have no idea how to confirm whether the automatic 4 retries mentioned there is already enabled, or how to configure it further.  Can someone help out?

**To Reproduce**
N/A this is a request for documentation

**Expected behavior**
I would like clear documentation about how to configure retries

**Screenshots**
N/A

**Must gather (please complete the following information):**
 - SDK Version 0.6.0
 - Node.js Version v18.18.0
 - Name of service that you're trying to use @ibm-cloud/cloudant
 - Name of operation that you're trying to invoke :  Multiple - reading and posting documents

**Additional context**
Not sure I have much more to add.

**Comment by andrewmartin000** [comment]
I just realised that there is slightly more documentation available if I search for "retries" rather than "retry" - but I still can't find a good example or details about how to validate it.

**Comment by mojito317** [comment]
Hi @andrewmartin000!

On the client side you can [enable the DEBUG mode](https://github.com/IBM/node-sdk-core#logging) to count and ensure how many retries happened, this shows you the HTTP response codes as well.

If you are looking for how you would configure a custom retry interval or the maximum number of retries, you can see an example under [Automatic retries > Programmatically > Node.js](https://github.com/IBM/ibm-cloud-sdk-common#programmatically) (also [highlighted link](https://github.com/IBM/ibm-cloud-sdk-common/#automatic-retries:~:text=To%20enable%20automatic%20retries%20programmatically%20in%20the%20Node%20SDK%2C%20use%20the%20service%20client%27s%20%60enableRetries()%60%20method%2C%20as%20in%20this%20example%3A))

**Comment by andrewmartin000** [comment]
Hi @mojito317  thanks for the update.

I did find that "Automatic Retries" section that you linked to  (although only after a long time searching).....  I was about to reply saying that the example there shows how to do it for a different library module, and not the Cloudant one.  

But now I re-read the example I see that it's "ExampleService" - so probably not a real service at all.

Anyway - I think I have what I need, so thanks very much.

I would still recommend a change to the actual cloudant module documentation to mention that automatic retries are possible and maybe a direct link to that other readme...

**Comment by ricellis** [comment]
>I am connecting to databases and getting socket hang up errors. I understand this is probably a network issue and I just need to retry.

It may be worth investigating whether your failing requests are clustered to a specific request type (e.g. only `find`). It may be that something like an inefficient query is causing the server to hang up at a timeout rather than a networking issue.

**Comment by mojito317** [comment]
> I would still recommend a change to the actual cloudant module documentation to mention that automatic retries are possible and maybe a direct link to that other readme...

@andrewmartin000 we added a section to our README as per your request: https://github.com/IBM/cloudant-node-sdk?tab=readme-ov-file#automatic-retries
