### ISSUE TITLE
Can this library move to v1 now?

### ISSUE THREAD

**Issue by alexross1988** [IBM/cloudant-node-sdk#1376]
I'm aware on https://www.npmjs.com/package/@ibm-cloud/cloudant it states..
> Disclaimer: This library is still a 0.x release. We do consider this library production-ready and capable, but there are still some limitations we’re working to resolve, and refinements we want to deliver. We are working really hard to minimise the disruption from now until the 1.0 release, but there may still be some changes that impact applications using this SDK. For now, be sure to pin versions to avoid surprises.

It's been three years now, can this library move to a v1 release so with our use of `^` in `package.json` we automatically get the latest minor/patch releases please?

**Comment by ricellis** [comment]
FWIW `^` in `package.json` allows ["changes that do not modify the left-most non-zero digit"](https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004) so it does automatically get patch releases for `0.x` versions.

There are some other API changes we need to make before we can freeze the API, we're working on it.
