### ISSUE TITLE
Add Node 15 to the tested node versions

### ISSUE THREAD

**Issue by vmatyusGitHub** [IBM/cloudant-node-sdk#145]
As can be seen from the release plan of Node:
https://nodejs.org/en/about/releases/
From 2020-10-20, Node 15 is available. 
Currently, Travis checks version 10,12 and 14.
It would be good to extend the list with also version 15 to check whether this SDK is compatible with it.

**Comment by ricellis** [comment]
I edited the title ~supported~ -> tested

Recalling from your link above:
>Production applications should only use Active LTS or Maintenance LTS releases.

I agree we should add 15 to the travis checks to get a warning of any problems that will hit us in LTS 16 when it is available in April, but we should not change the support statement.
