### ISSUE TITLE
Regression encountered updating from v0.10.1 to v0.10.2: SyntaxError: Named export 'CloudantV1' not found

### ISSUE THREAD

**Issue by mpawlow** [IBM/cloudant-node-sdk#1631]
**Describe the bug**

- Using v0.10.2 crashes the Node app with a Syntax error

```shell
$ node index.js
file:///C:/Users/016908649/git/dsx-service-broker/node_modules/@dap/cloudant-client/lib/cloudant-client.mjs:17
import { CloudantV1 } from "@ibm-cloud/cloudant";
         ^^^^^^^^^^
SyntaxError: Named export 'CloudantV1' not found. The requested module '@ibm-cloud/cloudant' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@ibm-cloud/cloudant';
const { CloudantV1 } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:146:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:229:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)

Node.js v20.17.0
```

**To Reproduce**

- (1) Install v0.10.2 via npm
- (2) Start Node app
   - BUG: App crashes with syntax error

**Expected behavior**

- No syntax errors

**Screenshots**

![image](https://github.com/user-attachments/assets/b8747b78-687a-422d-884a-51c93e6481e6)

**Must gather (please complete the following information):**
 - SDK Version 0.10.2
 - Node.js Version 20.17.0
 - Name of service that you're trying to use (if applicable)
 - Name of operation that you're trying to invoke (if applicable)

**Additional context**

- WORKAROUND: Downgrade to v0.10.1

```shell
$ npm list @ibm-cloud/cloudant
dsx-service-broker@2.80.0 C:\Users\016908649\git\dsx-service-broker
`-- @dap/cloudant-client@2.1.0 overridden
  `-- @ibm-cloud/cloudant@0.10.1 overridden
```

**Comment by eiri** [comment]
@mpawlow Thank you for the report, I'll make a new release with a fix shortly.

**Comment by eiri** [comment]
Should be fixed in https://www.npmjs.com/package/@ibm-cloud/cloudant/v/0.10.3

**Comment by mpawlow** [comment]
Thanks @eiri  🙏
