### ISSUE TITLE
Getting `Request body is not properly gzipped` while creating a replication

### ISSUE THREAD

**Issue by madi031** [IBM/cloudant-node-sdk#235]
I am trying to create a replication in my Cloudant and when I call `postReplicate` method I am getting an error `400` with the message `Request body is not properly gzipped`.

Steps to replicate:
    - Try creating a DB replication in any of the existing Cloudant service

**Comment by ricellis** [comment]
The server (CouchDB versions <= 3.1.1; Cloudant (Classic) <= 8169) incorrectly processes gzip compressed request bodies for some endpoints. A server-side fix is on the way, we will update the known issues to make a note of this.

In the meantime the workaround is to disable request body compression:
```js
client.setEnableGzipCompression(false);
```
