### ISSUE TITLE
postSearch - does not work

### ISSUE THREAD

**Issue by virenvala** [IBM/cloudant-node-sdk#396]
Tried using postSearch with latest version [https://cloud.ibm.com/apidocs/cloudant?code=node#postsearch](https://cloud.ibm.com/apidocs/cloudant?code=node#postsearch)
But returns with error:
```
  status: 501,
  code: 501,
  body: '{"error":"not_implemented","reason":"this feature is not yet implemented"}'
```
Is that going to be available soon ?

**Comment by mojito317** [comment]
Hi @virenvala! Thanks for reporting, and congrats on raising your first-ever issue! 

Right now search is only available in _Cloudant Classic_. You can also reach the feature in _CouchDB_ if a running search plugin is connected to each cluster node. However _Transaction Engine_ does support search at the moment. In my understanding, it is in their backlog, and the work is not scheduled yet, but I am not an expert on the topic, so if you are trying to use Transaction Engine then you should contact Cloudant support (either via the dashboard or at support@cloudant.com).

If it is not TE can you share the name of the service that you're trying to use (Cloudant Classic/CouchDB).

It also would be nice to know which version of the service you are using.

**Comment by mojito317** [comment]
As we discussed offline this is a TE issue. Closing this.
