### ISSUE TITLE
Support for retry mechanism in SDK

### ISSUE THREAD

**Issue by saristar** [IBM/cloudant-node-sdk#410]
**Is your feature request related to a problem? Please describe.**
My current project was using `nodejs-cloudant` library and since it is deprecated I'm shifting to `IBM cloudant-node-sdk`. I was using some of the plugins from the library and one of it is `retry`. Currently I do not see any retry mechanism in the new SDK.

**Describe the solution you'd like**
Like in previous library where there was support for retry mechanism using a plugin, it would be better if we have similar retry mechanism in this SDK.

**Comment by ricellis** [comment]
This feature is going to be provided from the [`node-sdk-core`](https://github.com/IBM/node-sdk-core) to reach parity with the [other SDKs](https://nodejs.org/api/errors.html#errors_err_invalid_arg_value).

If you need the feature immediately you can temporarily workaround the limitation by using an axios retry plugin e.g. [`axios-retry`](https://www.npmjs.com/package/axios-retry) or [`retry-axios`](https://www.npmjs.com/package/retry-axios) and applying it directly to the SDK's underlying `axios` instance e.g. where `client` is your `CloudantV1` instance:
```javascript
const rax = require('retry-axios');
client.requestWrapperInstance.axiosInstance.defaults.raxConfig = {
    // ... retry-axios config options
    instance: client.requestWrapperInstance.axiosInstance,
  };
rax.attach(client.requestWrapperInstance.axiosInstance);
```
or
```javascript
const axiosRetry = require('axios-retry');
axiosRetry(client.requestWrapperInstance.axiosInstance, {
    // ... axios-retry config options
  },
});
```

**Comment by pheuberger** [comment]
Any alternatives for TypeScript users as this one fails, because TS doesn't allow me to access a private member of `BaseService`?

**Comment by ricellis** [comment]
Same as https://github.com/IBM/cloudant-node-sdk/issues/408#issuecomment-901750631 from the next release TS users will be able to get the axios instance to do a workaround until the core provides built-in retries.

**Comment by pheuberger** [comment]
Ah, brilliant! When is this going to be released?

**Comment by ricellis** [comment]
Hopefully no later than the end of the month.

**Comment by ricellis** [comment]
I'm going to close this as we've picked up the new `2.14.0` core via https://github.com/IBM/cloudant-node-sdk/pull/447. So we will have the [built-in retry capability](https://github.com/IBM/ibm-cloud-sdk-common/#automatic-retries) from the next `0.0.19` release.

**Comment by kvv002** [comment]
Hi @ricellis , when will 0.0.19 will be released?

**Comment by ricellis** [comment]
Hopefully sometime in the next week.

**Comment by kvv002** [comment]
Hi @ricellis , Does this release include more retry options other than **maxRetries, maxRetryInterval**, I wanted a parameter which could support **retryStatusCodes**, I have tried the same parameter which is supported by axios but it doesnt seem to work with enableRetries(), below is my sample snippet 
```
const { IamAuthenticator } = Authenticator
const authenticator = new IamAuthenticator({
    apikey: CLOUDANT_APIKEY
  })

const service = new CloudantV1({
authenticator: authenticator
})
service.setServiceUrl(CLOUDANT_URL);
service.enableRetries({ maxRetries: 2, maxRetryInterval: 100, statusCodesToRetry: [404] });
```

**Comment by ricellis** [comment]
The [`node-sdk-core`](https://github.com/IBM/node-sdk-core) uses `retry-axios` defaults of `statusCodesToRetry: [[100, 199], [429, 429], [500, 599]]`.

If you'd like to see an enhancement to the core to support configuration of alternative codes you can raise an issue there for discussion. Alternatively you can use the workaround above to configure custom retries instead of using the built-in support.

FWIW I can't think of anywhere in the API where it makes sense to retry a `404` - if your app is relying on that pattern I think a review might identify a more optimal design.

**Comment by kvv002** [comment]
@ricellis , that was just an example,  let me change it to another one like `statusCodesToRetry: [ENOTFOUND]`
