### ISSUE TITLE
Using key-regex to query documents in a database

### ISSUE THREAD

**Issue by kvv002** [IBM/cloudant-node-sdk#457]
Hi, 
Following the [documentation ](https://cloud.ibm.com/apidocs/cloudant?code=node#postalldocs), I am trying to query the documents using **key** filter with regex as below, but the regex doesn't seem to give an expected output.
If I add the full ID for the **key**, it works fine.
_key: Schema for a document ID.
Possible values: Value must match regular expression `[^_].*`
```
service.postAllDocs({
    db: 'test',
    includeDocs: true,
    limit: 10,
    attachments: false,
    conflicts: false,
    descending: false,
    att_encoding_info: true,
    key:'^small-appliances*'
  }).then(response => {
    console.log('get All docs:',JSON.stringify(response.result));
  });
```

Could you please help me understand where am I going wrong.
Thank you

**Comment by ricellis** [comment]
For `postAllDocs` the `key` must be a document ID - a regex is not acceptable there. The documentation you refer to is saying that the supplied document ID must match the regex `[^_].*` i.e. document IDs are not allowed to start with the `_` character. That is a general restriction on all document IDs in Cloudant and CouchDB.

**Comment by kvv002** [comment]
@ricellis , thanks for the quick help

**Comment by kvv002** [comment]
@mojito317 , that was helpful, thank you!

**Comment by kvv002** [comment]
Hi @mojito317 @ricellis ,
is it possible to fetch all documents except design documents using standard methods like **getDocument** or **postAllDocs**

**Comment by mojito317** [comment]
Hi @kvv002!

> 1. Is it possible to fetch all documents except design documents using standard methods like **getDocument** or **postAllDocs**

I would rather create and use a simple view because there are tricks with `postAllDocs` to get documents except for design documents, but it depends on your ids which approach is working (see [this](https://stackoverflow.com/questions/27545956/get-all-documents-in-a-couchdb-database-except-the-design-documents) and [this](https://github.com/pouchdb/pouchdb/issues/4943)). 
Create a view:
```js
const filterDesignDocsViewMap = {
  map: 'function(doc) { emit(doc._id, null); }'
}
const designDoc: CloudantV1.DesignDocument = {
  views: {'filterDesignDocsView': filterDesignDocsViewMap}
}
service.putDesignDocument({
  db: 'test',
  designDocument: designDoc,
  ddoc: 'filterDdoc'
}).then(response => {
  ...
});
```
Fetch the view with `include_docs: true`:
```js
service.postView({
  db: 'test',
  ddoc: 'filterDdoc',
  view: 'filterDesignDocsView',
  include_docs: true
}).then(response => {
  ...
});
```

> 2\. Is it possible to retrieve database which are partioned only and non-partiotioned only.

With `getAllDbs` no. But if you pass the list from the `getAllDbs` response to the `keys` of `postDbsInfo` then you can get the database is partitioned or not. Make sure you split the response of `getAllDbs` into chunks if there are more than 100 databases on your Cloudant instance:

```js
service.getAllDbs().then(response => {
  let array = response.result;
  let i,j, temporary, chunk = 100; // make chunks from the response list, because postDbsInfo cannot handle more than 100 keys
  for (i = 0,j = array.length; i < j; i += chunk) {
    temporary = array.slice(i, i + chunk);
    service.postDbsInfo({
      keys: temporary
    }).then(response => {
      for (db of response.result){
        let partitioned = db.info.props.partitioned ? "partitioned" : "not partitioned" ;
        console.log(`${db.info.db_name} is ${partitioned}`);
      }
    });  }
});
```

**Comment by kvv002** [comment]
Hi @mojito317 , May I know what is the default limit to retrieve all the documents?
