### ISSUE TITLE
Please guide us about official release dates for `cloudant-node-sdk` 

### ISSUE THREAD

**Issue by braj1999** [IBM/cloudant-node-sdk#463]
Hello, 

We have development an integrator  and have used https://github.com/cloudant/nodejs-cloudant#deprecated for Cloudant interactions. We recently got to know that this library is now deprecated and `cloudant-node-sdk` has been suggested as replacement.

Looking at readme of `cloudant-node-sdk`, it says - **This SDK is being released initially as a pre-release version. Changes might occur which impact applications that use this SDK.**

Could you please guide us on the official release plan so that we can move our integration to this SDK.

**Comment by mojito317** [comment]
Hi @braj1999!

Thanks for the question, all our plans are listed under the [Cloudant SDK Transition Blog Post](https://blog.cloudant.com/2021/06/30/Cloudant-SDK-Transition.html#summary-of-sdk-changes).

**Comment by braj1999** [comment]
@mojito317 thanks but I am not able to see a date when we can expect 1.x or say beta tag removed.

**Comment by mojito317** [comment]
Sorry, but I only can quote one of the sentences from the linked article for you:

> We consider these libraries production-ready and capable, but there are still some limitations we’re working to resolve, and refinements we want to deliver. We are working really hard to minimise the disruption from now until the 1.0 releases. For now, be sure to pin versions to avoid surprises.

**Comment by ricellis** [comment]
The [0.0.19 release](https://github.com/IBM/cloudant-node-sdk/releases/tag/v0.0.19) is not flagged `pre-release` and we've updated the `README` to better reflect the statement above from the blog post.
