### ISSUE TITLE
Get functions missing in library which were available in deprecated @cloudant/cloudant package

### ISSUE THREAD

**Issue by dtto86** [IBM/cloudant-node-sdk#598]
**Is your feature request related to a problem? Please describe.**
In older deprecated package @cloudant/cloudant, we had db.list() and db.listAsStream() functions to fetch all documents but in @ibm-cloud/cloudant package, to fetch all documents we have postAllDocs() and postAllDocsAsStream() functions.

**Describe the solution you'd like**
Is there any plan to introduce functions having name as getXXX?

**Comment by mojito317** [comment]
Hi @dtto86!

`GET` requests are intentionally excluded in the SDK in favor of `POST` requests when `GET` has an equivalent behavior as `POST`. There is no plan to introduce functions having name as getXXX where the postXXX is available.
