### ISSUE TITLE
The README file in this repo has a bad link - [404:NotFound] 

### ISSUE THREAD

**Issue by MrCull** [IBM/cloudant-node-sdk#77]
**Describe the bug**
The markup version of the readme that is displayed for the main page in this repo contains the following bad link:

"Node.js SDK Core document about authentication"
Status code [404:NotFound] - Link: https://github.com/IBM/node-sdk-core/blob/master/Authentication.md

It looks like case is important and this should be:
https://github.com/IBM/node-sdk-core/blob/master/AUTHENTICATION.md

**To Reproduce**
Click the link

**Expected behavior**
Link should work

**Screenshots**
N/A

**Must gather (please complete the following information):**
N/A

**Additional context**

I (a human) verified that this link is broken and have manually logged this Issue (i.e. this Issue has not been created by a bot).

This bad link was found by a tool I recently created as part of an new experimental hobby project: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder

Re-check this Repo using the tool’s website: http://githubreadmechecker.com/Home/Search?SingleRepoUri=https%3a%2f%2fgithub.com%2fIBM%2fcloudant-node-sdk

If you have any feedback on the tool itself, or the information provided here, then please feel free to share your thoughts by adding a comment here, or adding a “Discussions” comment in the tool’s Repo.

**Comment by bessbd** [comment]
https://github.com/IBM/node-sdk-core/pull/117 is now merged, so I'm closing this issue.
Thank you for bringing this to our attention, @MrCull !
