### ISSUE TITLE
Support for Node v18

### ISSUE THREAD

**Issue by hammoaj** [IBM/cloudant-node-sdk#827]
Current version of library doesn't support Node v18

Can be reproduced by installing on a platform running Node v18

Should install as normal

**Must gather (please complete the following information):**
 - SDK Version: 0.1.2
 - Node.js Version: 18

**Comment by eiri** [comment]
Current version of sdk supports node 18, here is travis node18 run from the latest `master` merge. https://app.travis-ci.com/github/IBM/cloudant-node-sdk/jobs/569050500

**Comment by ricellis** [comment]
Point of clarification on supports vs works.
We _don't support_ running on non-LTS versions as per [Node.js release guidance](https://nodejs.org/en/about/releases/):
>Production applications should only use Active LTS or Maintenance LTS releases.

Node.js 18 will not be the Active LTS unil October at which time we will update the [prereq statement in our README](https://github.com/IBM/cloudant-node-sdk#prerequisites) and the [`engine` requirements in our `package.json`](https://github.com/IBM/cloudant-node-sdk/blob/7f0518390417ed5f8b72313abb0807e4cfee9a93/package.json#L35). The engine requirements only prevent installation of the package if you are running in [strict mode](https://docs.npmjs.com/cli/v7/using-npm/config#engine-strict).

As @eiri points out we are regularly testing against Node.js 18. The current version of the SDK _works_ (i.e. operates normally) with that version, but it is not yet _supported_.
