### ISSUE TITLE
Exclude `.ts` source files from releases

### ISSUE THREAD

**Issue by bessbd** [IBM/cloudant-node-sdk#9]
The presence of `.ts` original source files is causing issues for some users.
The task is to exclude `.ts` files in https://github.com/IBM/cloudant-node-sdk/blob/master/.npmignore (but not `.d.ts`).

See also the discussion at https://github.com/microsoft/TypeScript/issues/12358 .

**Comment by mojito317** [comment]
Since the README-s are not including the imports right now, we should check whether this has an effect on importing when we are using Typescript.
